baseurl = "https://devorchestra.github.io/the-scrum-dao/"
title = "The Scrum DAO"
themesDir = "themes"
theme = "github"
publishDir = "../docs"

[params]
    description = "Flexible software development methodology (Scrum) and Decentralized Autonomous Organizations (DAO)"
    author_url = "https://github.com/devOrchestra"
    project_url = "https://github.com/devOrchestra/the-scrum-dao"
    project_documentation = "https://github.com/devOrchestra/the-scrum-dao"
    github_project_name = "the-scrum-dao"
    github_user_name = "https://github.com/devOrchestra"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
